# Generated by Django 4.2.3 on 2023-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='user/'),
        ),
    ]
