# Generated by Django 4.2.3 on 2023-08-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_is_blocked_alter_user_display_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(blank=True, default='user/user.png', null=True, upload_to='user/'),
        ),
    ]
